[tool.black]
verbose = true
line-length = 79
target-version = ['py38', 'py39']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
    /(
        \.eggs  # Exclude a few common directories in the root of the project
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.pylint.messages_control]
disable = [
    'too-few-public-methods'
]

[tool.pylint.format]
max-line-length = '79'

[tool.pylint .MASTER]
init-hook = 'import sys, os; sys.path.append(os.path.dirname(os.path.realpath("__file__")))'
jobs = 0

[tool.pytest.ini_options]
minversion = '6.0'
addopts = '-rap --strict-markers'
testpaths = [
    'tests'
]
required_plugins = [
    'pytest-dotenv'
]
env_override_existing_values = 1
env_files = [
    '.dev.env'
]
# Logging
log_file_level = 'DEBUG'
log_file = '/tmp/pytest'
log_file_format = '%(asctime)s %(levelname)s %(message)s'
log_file_date_format = '%m-%d-%Y %H:%M:%S'
filterwarnings = [
    'ignore::urllib3.exceptions.InsecureRequestWarning'
]
